### ISSUE TITLE
Dashboard category circles in green and red

### ISSUE THREAD

**Issue by henhuy** [rl-institut/E_Metrobus#262]
Show correct and incorrect answers as circle arcs around category

**Comment by henhuy** [comment]
I'm going to implement arcs per question.
What is our "red" color in hex?

**Comment by bmlancien** [comment]
For green, use: #17BEBB
For red: #E46C6C

I find it better if we accumulate the right and wrong answers. For example, if there are 4 questions in a category and the user answered the 1st and 3 questions wrong, the 2nd and 4th questions right, it would be better to have one half of the circle green and the other half red instead of one quarter red, one quarter green, another quarter red, etc... Because it could look too overloaded and colorful. Simple is better!

And could you also implement that on the top line below the header on the question pages? Same principle as the circles on the dashboard, but in a form of a line, of course (if the 3 colors are present, keep green on the left, red in the middle and gray on the right side)
