### ISSUE TITLE
Add optional language english

### ISSUE THREAD

**Issue by henhuy** [rl-institut/E_Metrobus#84]
TODOS: 
- [x] Add language support
- [ ] Add "change language" button to landing page
- [ ] Add "change language" button to top bar

**Comment by henhuy** [comment]
@bmlancien could you provide a switch button? Where shall we put it?

**Comment by bmlancien** [comment]
That's a bit difficult to add a new item to a layout with not so much space... So I thought of adding it to  2 places:
- On the first page, at the end of the animation (after button on footer has been displayed)
- On onboarding page, instead of the back-to-button on top left (right now it leads to the dashboard itself, so it has no use) -> opens pop-up with 2 radio buttons

Have a look at the screenshots or at the Figma board.

Basically, when the DE flag is displayed on top on the dashboard, the app is in German. When the UK flag is displayed, the app is in English.

@henhuy What do you think? Does that make sense? Is that technically makeable? If yes, @mdrli could start implementing it.

![LP_De](https://user-images.githubusercontent.com/33999424/73946030-8c85fc80-48f5-11ea-9c03-d7eed19f8f5a.png)

![LP_En](https://user-images.githubusercontent.com/33999424/73946038-90198380-48f5-11ea-9fb3-038f9dff262b.png)

![Dashboard_De (1)](https://user-images.githubusercontent.com/33999424/73946057-97d92800-48f5-11ea-9d9f-427a949c3ef4.png)

![Dashboard_De](https://user-images.githubusercontent.com/33999424/73946084-a3c4ea00-48f5-11ea-8ca0-38d5e7fa5e29.png)

![Dashboard_En (1)](https://user-images.githubusercontent.com/33999424/73946093-a7f10780-48f5-11ea-8d28-1441558ed953.png)

![Dashboard_En](https://user-images.githubusercontent.com/33999424/73946103-ac1d2500-48f5-11ea-99d6-c2a4ce70ff7b.png)

**Comment by henhuy** [comment]
Hi @bmlancien - that was quick :)
Personally, I like first solution (on first page) the most... but you are the designer ;)
Both implementations are easy...

**Comment by henhuy** [comment]
@mdrli can you implement the first suggestion with icons from mail?
You can use PR #86

**Comment by bmlancien** [comment]
@henhuy Actually the idea was to implement both ideas :) Because the user should be able to switch the language while using the app, and not just at the beginning. And the dashboard is the best place for this because it is basically the central piece of the app.

@mdrli Can you also implement the second idea? Thanks!

**Comment by henhuy** [comment]
> Actually the idea was to implement both ideas

Ah okay! Fine.

**Comment by henhuy** [comment]
On my screen, "switch to english" icon and button disappear behind "Toll, dass du mit einem E-Bus fährst!" screen. Could you fix it, @mdrli ?
Additionally, we decided to have change language button in top bar. thx!

**Comment by mdrli** [comment]
@henhuy I have tried to fix, does it work?

> Additionally, we decided to have change language button in top bar. thx!
I gonna try this again today.

**Comment by henhuy** [comment]
Still a bit hidden - sorry:
![grafik](https://user-images.githubusercontent.com/17476051/74433333-7da4ca00-4e60-11ea-85e7-1ba3d1db5108.png)

**Comment by mdrli** [comment]
How do you get the Bug? I din't get it, after I merged the dev. @henhuy

**Comment by henhuy** [comment]
Maybe we should remove radiobuttons and have simple buttons? @bmlancien ?
![grafik](https://user-images.githubusercontent.com/17476051/74434896-a5e1f800-4e63-11ea-99ca-a992b11025c5.png)

**Comment by mdrli** [comment]
@henhuy does it now look right?
I also fixed the position of the top bar switch, is it okay?

**Comment by henhuy** [comment]
> @henhuy does it now look right?
> I also fixed the position of the top bar switch, is it okay?

thx. That is okay!

**Comment by bmlancien** [comment]
> Maybe we should remove radiobuttons and have simple buttons? @bmlancien ?

@henhuy yes, if that's a problem, we an try with buttons too

**Comment by henhuy** [comment]
I just thought to remove popup, as for now, we only switch between two languages?!
Additionally, it feels weird to click on switch to english and a popup opens giving me option to switch to german...
Maybe just switch by clicking on button?

**Comment by bmlancien** [comment]
Ok, we can try this way
